//! Turning a resolved palette into a GTK stylesheet.
//!
//! Two constraints shape everything here, and neither is negotiable:
//!
//! **No CSS custom properties.** `var()` only exists from GTK 4.15.1, and
//! f3note targets a GTK 4.12 API floor so it can ship native packages on
//! openSUSE Leap 15.6, Ubuntu 24.04 and RHEL 10. Every color is therefore
//! written out as a literal. Since the stylesheet is generated anyway, this
//! costs nothing.
//!
//! **Palette values never reach CSS unchecked.** Themes are third-party files.
//! A value like `red; } * { background: url(http://…) }` would otherwise be
//! substituted straight into a stylesheet. `Palette::parse` restricts values to
//! a character set that cannot close a declaration, and `rgba()` below re-parses
//! hex rather than interpolating it. The property names are fixed by this
//! template; only values come from the theme. On GTK before 4.22 a malformed
//! stylesheet does not merely fail to apply — it aborts the process — so the
//! caller validates the result before installing it.

use super::font::Font;
use super::Palette;

/// Convert `#rrggbb` to a CSS `rgba()` with the given alpha.
///
/// Re-parsing the hex rather than pasting the string is deliberate: it means a
/// value that somehow got through validation still cannot reach the stylesheet
/// as text. Anything unparseable falls back to the supplied default.
fn rgba(hex: &str, alpha: f64, fallback: (u8, u8, u8)) -> String {
    let parsed = (|| {
        let h = hex.strip_prefix('#')?;
        if h.len() != 6 {
            return None;
        }
        Some((
            u8::from_str_radix(&h[0..2], 16).ok()?,
            u8::from_str_radix(&h[2..4], 16).ok()?,
            u8::from_str_radix(&h[4..6], 16).ok()?,
        ))
    })();
    let (r, g, b) = parsed.unwrap_or(fallback);
    let a = alpha.clamp(0.0, 1.0);
    if a >= 1.0 {
        format!("#{r:02x}{g:02x}{b:02x}")
    } else {
        format!("rgba({r},{g},{b},{a:.3})")
    }
}

/// Same, but always emits an opaque literal.
fn solid(hex: &str, fallback: (u8, u8, u8)) -> String {
    rgba(hex, 1.0, fallback)
}

pub struct Appearance<'a> {
    pub palette: &'a Palette,
    pub font: &'a Font,
    /// Window background alpha. 1.0 is opaque; lower values let a compositor
    /// blur rule show through.
    pub opacity: f64,
}

pub fn stylesheet(a: &Appearance) -> String {
    let p = a.palette;

    let bg = p.get_or("background", "#1e1e1e");
    let fg = p.get_or("foreground", "#d0d0d0");
    let lighter = p.get_or("lighter_background", &bg);
    let darker = p.get_or("dark_background", &bg);
    let muted = p.get_or("muted", "#808080");
    let accent = p.get_or("accent", &fg);
    let selection = p.get_or("selection", &lighter);
    let sel_fg = p.get_or("selection_foreground", &fg);
    let cursor = p.get_or("cursor", &fg);
    let red = p.get_or("red", "#cc4444");
    let yellow = p.get_or("yellow", "#ccaa44");

    // The window carries the alpha; every surface inside it is transparent so
    // one translucent layer reaches the compositor instead of several stacked
    // ones, which would multiply into an almost opaque result.
    let window_bg = rgba(&bg, a.opacity, (30, 30, 30));
    let bar_bg = rgba(&darker, a.opacity, (24, 24, 24));

    let fg = solid(&fg, (208, 208, 208));
    let muted = solid(&muted, (128, 128, 128));
    let accent = solid(&accent, (122, 162, 247));
    let selection = solid(&selection, (60, 60, 60));
    let sel_fg = solid(&sel_fg, (255, 255, 255));
    let cursor = solid(&cursor, (208, 208, 208));
    let lighter_solid = solid(&lighter, (40, 40, 40));
    let red = solid(&red, (204, 68, 68));
    let yellow = solid(&yellow, (204, 170, 68));
    // A hairline that reads as a separator against either a light or dark
    // background, without needing a second palette key.
    let hairline = rgba(&muted, 0.25, (128, 128, 128));
    let hover = rgba(&muted, 0.18, (128, 128, 128));

    format!(
        "\
/* Generated by f3note. Edits are overwritten on the next theme change. */

window.f3note {{
  background-color: {window_bg};
  color: {fg};
  font-family: {family};
  font-size: {size}pt;
}}

/* The text area stays fully transparent so the window's alpha is the only
   translucent layer. Setting a background here would stack with it. */
window.f3note textview,
window.f3note textview text {{
  background-color: transparent;
  color: {fg};
  caret-color: {cursor};
}}

window.f3note textview text selection,
window.f3note textview text selection:focus {{
  background-color: {selection};
  color: {sel_fg};
}}

/* Line numbers: present but recessive. The active line's number takes the
   foreground color so the eye can find the caret without a highlight bar. */
window.f3note textview border,
window.f3note .gutter {{
  background-color: transparent;
  color: {muted};
}}

window.f3note .f3note-banner {{
  background-color: {bar_bg};
  color: {fg};
  border-bottom: 1px solid {hairline};
  padding: 4px 10px;
}}
window.f3note .f3note-banner.warning {{ color: {yellow}; }}
window.f3note .f3note-banner.error {{ color: {red}; }}
window.f3note .f3note-banner button {{
  background: none;
  border: none;
  box-shadow: none;
  color: {accent};
  padding: 0 6px;
  min-height: 0;
}}
window.f3note .f3note-banner button:hover {{ background-color: {hover}; }}

window.f3note .f3note-statusbar {{
  background-color: {bar_bg};
  color: {muted};
  border-top: 1px solid {hairline};
  padding: 2px 10px;
  font-size: {small}pt;
}}

window.f3note .f3note-findbar {{
  background-color: {bar_bg};
  border-top: 1px solid {hairline};
  padding: 3px 8px;
}}
window.f3note .f3note-findbar entry {{
  background-color: transparent;
  color: {fg};
  border: none;
  box-shadow: none;
  outline: none;
  min-height: 0;
  padding: 2px 4px;
}}
window.f3note .f3note-findbar entry:focus {{ box-shadow: none; }}
window.f3note .f3note-findbar entry.no-match {{ color: {red}; }}
window.f3note .f3note-findbar label {{ color: {muted}; }}

/* Tabs. Compact, no gradients, no rounded chrome: the active tab is marked by
   an accent underline rather than a raised shape. */
window.f3note notebook > header {{
  background-color: {bar_bg};
  border: none;
  box-shadow: none;
  padding: 0;
  min-height: 0;
}}
window.f3note notebook > header > tabs > tab {{
  background-color: transparent;
  color: {muted};
  border: none;
  border-bottom: 2px solid transparent;
  box-shadow: none;
  outline: none;
  min-height: 0;
  padding: 3px 10px;
  margin: 0;
}}
window.f3note notebook > header > tabs > tab:hover {{ background-color: {hover}; }}
window.f3note notebook > header > tabs > tab:checked {{
  background-color: {lighter_solid};
  color: {fg};
  border-bottom: 2px solid {accent};
}}
/* The modified marker: name prefixed with '*' and tinted with the accent, the
   same color the theme uses everywhere else to mean 'look here'. */
window.f3note notebook > header > tabs > tab label.modified {{ color: {accent}; }}
window.f3note notebook > header > tabs > tab button {{
  background: none;
  border: none;
  box-shadow: none;
  color: {muted};
  opacity: 0;
  min-height: 0;
  min-width: 0;
  padding: 0 2px;
}}
window.f3note notebook > header > tabs > tab:hover button {{ opacity: 1; }}
window.f3note notebook > header > tabs > tab button:hover {{ color: {red}; }}
window.f3note notebook > stack {{ background-color: transparent; }}

window.f3note scrollbar {{ background-color: transparent; }}
window.f3note scrollbar slider {{
  background-color: {hairline};
  border: none;
  min-width: 6px;
  min-height: 6px;
}}
window.f3note scrollbar slider:hover {{ background-color: {muted}; }}

/* Ctrl+P switcher. A list, not a dialog. */
window.f3note .f3note-switcher {{
  background-color: {bar_bg};
  border: 1px solid {hairline};
}}
window.f3note .f3note-switcher row {{
  background-color: transparent;
  color: {fg};
  padding: 3px 10px;
}}
window.f3note .f3note-switcher row:selected {{
  background-color: {selection};
  color: {sel_fg};
}}
window.f3note .f3note-switcher row label.path {{ color: {muted}; }}
",
        family = a.font.family,
        size = a.font.size,
        small = (a.font.size - 2).max(6),
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::theme::Mode;

    fn sample() -> Palette {
        Palette::parse(
            r##"
mode = "dark"
background = "#1a1b26"
foreground = "#a9b1d6"
accent = "#7aa2f7"
"##,
        )
    }

    #[test]
    fn emits_literal_colors_never_custom_properties() {
        let f = Font::default();
        let css = stylesheet(&Appearance {
            palette: &sample(),
            font: &f,
            opacity: 1.0,
        });
        assert!(!css.contains("var("), "stylesheet must not use var()");
        assert!(css.contains("#1a1b26"));
        assert!(css.contains("#7aa2f7"));
    }

    #[test]
    fn opacity_below_one_produces_rgba_on_the_window_only() {
        let f = Font::default();
        let css = stylesheet(&Appearance {
            palette: &sample(),
            font: &f,
            opacity: 0.85,
        });
        assert!(css.contains("rgba(26,27,38,0.850)"));
        // The text view must stay fully transparent rather than gaining its own
        // alpha, or the two layers would compound.
        assert!(css.contains("background-color: transparent"));
    }

    #[test]
    fn a_hostile_palette_value_cannot_reach_the_stylesheet() {
        let p = Palette::parse(
            r##"
background = "#111111"
foreground = "} * { background-image: url(http://evil/x) } x {"
"##,
        );
        let f = Font::default();
        let css = stylesheet(&Appearance {
            palette: &p,
            font: &f,
            opacity: 1.0,
        });
        assert!(!css.contains("evil"));
        assert!(!css.contains("url("));
    }

    #[test]
    fn falls_back_to_readable_colors_for_an_empty_palette() {
        let p = Palette::parse("");
        let f = Font::default();
        let css = stylesheet(&Appearance {
            palette: &p,
            font: &f,
            opacity: 1.0,
        });
        assert!(css.contains("window.f3note"));
        assert!(!css.contains("color: ;"));
        assert!(!css.contains("background-color: ;"));
        assert_eq!(p.mode, Mode::Dark);
    }
}
