//! Generating a GtkSourceView style scheme from the palette.
//!
//! CSS is not enough on its own. GtkSourceView draws the line-number gutter,
//! the current-line highlight, bracket matching, search results and all syntax
//! colors from a *style scheme*, which is an XML document, not a stylesheet. To
//! have one palette drive the whole editor, f3note generates a scheme to match
//! the CSS it just generated.
//!
//! One rule matters more than the rest: **the `text` style must not carry a
//! background.** A background there is painted by the widget and would sit on
//! top of the window's translucent CSS background, silently defeating the
//! transparency option. Leaving it unset lets the window's alpha be the only
//! thing between the text and the compositor.

use super::Palette;

/// Escape the five characters that are special in XML content and attributes.
///
/// Palette values are already restricted to a safe character set by
/// `Palette::parse`, so this is belt and braces — but this function writes a
/// document consumed by a real XML parser, and a generator that cannot be
/// trusted with arbitrary input is a generator waiting to break.
fn esc(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&apos;"),
            _ => out.push(c),
        }
    }
    out
}

pub const SCHEME_ID: &str = "f3note";

pub fn generate(p: &Palette) -> String {
    let c = |key: &str, fallback: &str| esc(p.get(key).unwrap_or(fallback));

    let fg = c("foreground", "#d0d0d0");
    let bright_fg = c("bright_foreground", &fg);
    let muted = c("muted", "#808080");
    let accent = c("accent", &fg);
    let selection = c("selection", "#3c3c3c");
    let sel_fg = c("selection_foreground", &bright_fg);
    let lighter = c("lighter_background", "#282828");
    let red = c("red", "#cc4444");
    let green = c("green", "#44cc44");
    let yellow = c("yellow", "#ccaa44");
    let blue = c("blue", "#4444cc");
    let cyan = c("cyan", "#44cccc");
    let magenta = c("magenta", "#cc44cc");
    let orange = c("orange", &yellow);

    format!(
        r#"<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by f3note from the active system palette. Do not edit: this file
     is rewritten whenever the theme changes. -->
<style-scheme id="{SCHEME_ID}" name="f3note" version="1.0">
  <author>f3note</author>
  <description>Follows the system palette</description>

  <!-- No background on `text`: see the module comment. The window's CSS owns
       the background so that the transparency option keeps working. -->
  <style name="text"                        foreground="{fg}"/>
  <style name="selection"                   foreground="{sel_fg}" background="{selection}"/>
  <style name="selection-unfocused"         foreground="{sel_fg}" background="{selection}"/>
  <style name="cursor"                      foreground="{bright_fg}"/>
  <style name="secondary-cursor"            foreground="{muted}"/>
  <style name="current-line"                background="{lighter}"/>
  <style name="current-line-number"         foreground="{fg}" bold="true"/>
  <style name="line-numbers"                foreground="{muted}"/>
  <style name="draw-spaces"                 foreground="{muted}"/>
  <style name="background-pattern"          background="{lighter}"/>

  <style name="bracket-match"               foreground="{accent}" bold="true"/>
  <style name="bracket-mismatch"            foreground="{red}" bold="true"/>
  <style name="search-match"                foreground="{sel_fg}" background="{accent}"/>

  <!-- Syntax. Off by default in f3note, but the scheme has to be complete for
       the moment a user turns it on. -->
  <style name="def:comment"                 foreground="{muted}" italic="true"/>
  <style name="def:shebang"                 foreground="{muted}" bold="true"/>
  <style name="def:doc-comment-element"     italic="true"/>
  <style name="def:constant"                foreground="{orange}"/>
  <style name="def:string"                  foreground="{green}"/>
  <style name="def:special-char"            foreground="{cyan}"/>
  <style name="def:character"               foreground="{green}"/>
  <style name="def:number"                  foreground="{orange}"/>
  <style name="def:floating-point"          foreground="{orange}"/>
  <style name="def:boolean"                 foreground="{orange}"/>
  <style name="def:identifier"              foreground="{blue}"/>
  <style name="def:function"                foreground="{blue}"/>
  <style name="def:builtin"                 foreground="{cyan}"/>
  <style name="def:statement"               foreground="{magenta}" bold="true"/>
  <style name="def:keyword"                 foreground="{magenta}" bold="true"/>
  <style name="def:operator"                foreground="{fg}"/>
  <style name="def:type"                    foreground="{yellow}"/>
  <style name="def:preprocessor"            foreground="{cyan}"/>
  <style name="def:error"                   foreground="{red}" bold="true"/>
  <style name="def:warning"                 foreground="{yellow}"/>
  <style name="def:note"                    foreground="{accent}" bold="true"/>
  <style name="def:underlined"              underline="single"/>
  <style name="def:heading"                 foreground="{accent}" bold="true"/>
  <style name="def:link-destination"        foreground="{cyan}" underline="single"/>

  <style name="diff:added-line"             foreground="{green}"/>
  <style name="diff:removed-line"           foreground="{red}"/>
  <style name="diff:location"               foreground="{accent}"/>
</style-scheme>
"#
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn text_style_has_no_background_so_transparency_survives() {
        let p = Palette::parse(r##"background = "#1a1b26""##);
        let xml = generate(&p);
        let text_line = xml
            .lines()
            .find(|l| l.contains(r#"name="text""#))
            .expect("a text style");
        assert!(
            !text_line.contains("background="),
            "the text style must not paint a background: {text_line}"
        );
    }

    #[test]
    fn carries_palette_colors_into_the_document() {
        let p = Palette::parse(r##"foreground = "#aabbcc""##);
        let xml = generate(&p);
        assert!(xml.contains(r##"foreground="#aabbcc""##));
        assert!(!xml.contains("<<"));
    }

    #[test]
    fn escapes_xml_metacharacters() {
        // Palette::parse rejects these, so drive the escaper directly: it is
        // the last line of defence if that validation is ever relaxed.
        assert_eq!(esc(r#"a<b>&"c'"#), "a&lt;b&gt;&amp;&quot;c&apos;");
    }

    #[test]
    fn produces_a_complete_scheme_from_an_empty_palette() {
        let xml = generate(&Palette::parse(""));
        assert!(xml.contains(r#"id="f3note""#));
        assert!(xml.contains("</style-scheme>"));
        assert!(!xml.contains(r#"foreground="""#));
    }
}
